# Generated by Django 5.2.6 on 2025-09-23 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sheepfold', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('milk', models.DecimalField(decimal_places=2, help_text='liter', max_digits=5)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='sheepfold.sheep')),
            ],
        ),
    ]
