# Generated by Django 5.2.6 on 2025-09-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='earing',
            field=models.BooleanField(default=False),
        ),
    ]
