# Generated by Django 5.2.6 on 2025-09-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0002_sheep_earing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='earing',
            field=models.CharField(default='no_earring', max_length=100),
        ),
    ]
