# Generated by Django 5.2.6 on 2025-10-15 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0003_alter_sheep_earing'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='birthdate',
            field=models.DateField(auto_now_add=True, default=datetime.date(2020, 1, 1)),
            preserve_default=False,
        ),
    ]
