# Generated by Django 5.2.6 on 2025-10-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0004_sheep_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
