# Generated by Django 5.2.6 on 2025-10-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0005_sheep_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheep',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='sheepfold.sheep'),
        ),
        migrations.CreateModel(
            name='BirthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('lambs', models.ManyToManyField(blank=True, related_name='birth_event', to='sheepfold.sheep')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='birth_events', to='sheepfold.sheep')),
            ],
        ),
    ]
