# Generated by Django 5.2.6 on 2025-10-19 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0006_sheep_mother_birthevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='age',
        ),
    ]
