# Generated by Django 5.2.6 on 2025-10-19 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheepfold', '0007_remove_sheep_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('milk', models.DecimalField(decimal_places=2, help_text='liter', max_digits=5)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk', to='sheepfold.sheep')),
            ],
        ),
    ]
